#! /bin/sh

case "$1" in
  start)
    echo "Starting device"
    python3 /usr/bin/Device.py &
    ;;
  stop)
    echo "Stopping device"
    killall python3
    ;;
  *)
    echo "Usage: /etc/init.d/example{start|stop}"
    exit 1
    ;;
esac

exit 0
